name: GG
channels:
  - conda-forge
  - defaults
  - pytorch
  - fastai
dependencies:
  - python=3.7
  - pip>=19.1.1
  - pytorch
  - torchvision
  - fastai
  - pip:
    - numpy
    - lyricsgenius
    - yellowbrick
    - pytorch-pretrained-bert
    - ipykernel
    - jupyter
    - jupyterlab

